app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  scrapperApiUrl: http://localhost:8081/api/scrapper  # URL для API Scrapper
  botApiUrl: http://localhost:8080/api/bot  # URL для API бота

spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    com.example: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
      file-name-pattern: logs/application-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: true
