app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapperApiUrl: http://localhost:8081/api/scrapper
  botApiUrl: http://localhost:8080/api/bot

scrapper:
  api:
    url: http://localhost:8081/api/scrapper

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
